name: Notify on any file change

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send ntfy notification
        run: |
          COMMIT_MESSAGE=$(jq -r '.head_commit.message' "$GITHUB_EVENT_PATH")
          curl -s -d "$COMMIT_MESSAGE" https://ntfy.sh/imgRenalAppChange
